version: "3"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
        - ./volumes/n8n_data:/home/node/.n8n 
    restart: unless-stopped
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped