version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    ports:
      - "1433:1433"
    env_file:
      - .env
    volumes:
      - ./volumes/sqlserver_data:/var/opt/mssql

  sqlpad:
    image: sqlpad/sqlpad:latest
    container_name: sqlpad
    restart: always
    ports:
      - "8082:3000"
    env_file:
      - .env
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
