version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    mem_limit: 1024m  # Limit memory usage to 1GB
    cpus: 1  # Limit CPU usage to 1 core
    ports:
      - "16543:80"  # Map port 16543 on the host to port 80 on the container
    network_mode: "host"
    env_file:
      - .env  # Load environment variables from a file
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin  # Persist pgAdmin data

volumes:
  postgres_data:
  pgadmin_data:
